# Generated by Django 5.2 on 2025-04-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='mobile',
            new_name='mob',
        ),
    ]
