# Generated by Django 5.2 on 2025-04-24 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performs',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performing_doctors', to='operation.operation'),
        ),
        migrations.AlterUniqueTogether(
            name='performs',
            unique_together={('doctor', 'operation')},
        ),
    ]
