# Generated by Django 5.2 on 2025-04-24 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_doctor_passed_from'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Performs',
        ),
    ]
